# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TIPE_Hex_QT/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TIPE(object):
    def setupUi(self, TIPE):
        TIPE.setObjectName("TIPE")
        TIPE.resize(1083, 672)
        self.centralWidget = QtWidgets.QWidget(TIPE)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.horizontalLayoutView = QtWidgets.QHBoxLayout()
        self.horizontalLayoutView.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayoutView.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayoutView.setSpacing(6)
        self.horizontalLayoutView.setObjectName("horizontalLayoutView")
        self.labelView = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelView.sizePolicy().hasHeightForWidth())
        self.labelView.setSizePolicy(sizePolicy)
        self.labelView.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelView.setObjectName("labelView")
        self.horizontalLayoutView.addWidget(self.labelView)
        self.pushButtonViewDefault = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonViewDefault.setCheckable(True)
        self.pushButtonViewDefault.setChecked(False)
        self.pushButtonViewDefault.setObjectName("pushButtonViewDefault")
        self.horizontalLayoutView.addWidget(self.pushButtonViewDefault)
        self.pushButtonViewPlayer1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonViewPlayer1.setCheckable(True)
        self.pushButtonViewPlayer1.setObjectName("pushButtonViewPlayer1")
        self.horizontalLayoutView.addWidget(self.pushButtonViewPlayer1)
        self.pushButtonViewPlayer2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonViewPlayer2.setCheckable(True)
        self.pushButtonViewPlayer2.setObjectName("pushButtonViewPlayer2")
        self.horizontalLayoutView.addWidget(self.pushButtonViewPlayer2)
        self.gridLayout.addLayout(self.horizontalLayoutView, 1, 0, 1, 1)
        self.progressBarMinimax = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBarMinimax.setEnabled(True)
        self.progressBarMinimax.setProperty("value", 0)
        self.progressBarMinimax.setObjectName("progressBarMinimax")
        self.gridLayout.addWidget(self.progressBarMinimax, 9, 0, 1, 1)
        self.formLayoutNewGame = QtWidgets.QFormLayout()
        self.formLayoutNewGame.setContentsMargins(11, 11, 11, 11)
        self.formLayoutNewGame.setSpacing(6)
        self.formLayoutNewGame.setObjectName("formLayoutNewGame")
        self.labelPlayer1 = QtWidgets.QLabel(self.centralWidget)
        self.labelPlayer1.setObjectName("labelPlayer1")
        self.formLayoutNewGame.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelPlayer1)
        self.comboBoxPlayer1 = QtWidgets.QComboBox(self.centralWidget)
        self.comboBoxPlayer1.setObjectName("comboBoxPlayer1")
        self.formLayoutNewGame.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxPlayer1)
        self.labelPlayer2 = QtWidgets.QLabel(self.centralWidget)
        self.labelPlayer2.setObjectName("labelPlayer2")
        self.formLayoutNewGame.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelPlayer2)
        self.comboBoxPlayer2 = QtWidgets.QComboBox(self.centralWidget)
        self.comboBoxPlayer2.setObjectName("comboBoxPlayer2")
        self.formLayoutNewGame.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBoxPlayer2)
        self.pushButtonNewGame = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonNewGame.setObjectName("pushButtonNewGame")
        self.formLayoutNewGame.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pushButtonNewGame)
        self.labelMinimaxDepthPlayer1 = QtWidgets.QLabel(self.centralWidget)
        self.labelMinimaxDepthPlayer1.setObjectName("labelMinimaxDepthPlayer1")
        self.formLayoutNewGame.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelMinimaxDepthPlayer1)
        self.spinBoxMinimaxDepthPlayer1 = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBoxMinimaxDepthPlayer1.setMinimum(1)
        self.spinBoxMinimaxDepthPlayer1.setObjectName("spinBoxMinimaxDepthPlayer1")
        self.formLayoutNewGame.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxMinimaxDepthPlayer1)
        self.labelMinimaxDepthPlayer2 = QtWidgets.QLabel(self.centralWidget)
        self.labelMinimaxDepthPlayer2.setObjectName("labelMinimaxDepthPlayer2")
        self.formLayoutNewGame.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelMinimaxDepthPlayer2)
        self.spinBoxMinimaxDepthPlayer2 = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBoxMinimaxDepthPlayer2.setMinimum(1)
        self.spinBoxMinimaxDepthPlayer2.setObjectName("spinBoxMinimaxDepthPlayer2")
        self.formLayoutNewGame.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBoxMinimaxDepthPlayer2)
        self.gridLayout.addLayout(self.formLayoutNewGame, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 10, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.pushButtonPlay = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonPlay.setObjectName("pushButtonPlay")
        self.gridLayout.addWidget(self.pushButtonPlay, 5, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.centralWidget)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayout.addWidget(self.listWidget, 7, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 6, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 4, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.graphicsViewDefault = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsViewDefault.setEnabled(True)
        self.graphicsViewDefault.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.graphicsViewDefault.setObjectName("graphicsViewDefault")
        self.horizontalLayout.addWidget(self.graphicsViewDefault)
        self.graphicsViewPlayer1 = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsViewPlayer1.setEnabled(True)
        self.graphicsViewPlayer1.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.graphicsViewPlayer1.setObjectName("graphicsViewPlayer1")
        self.horizontalLayout.addWidget(self.graphicsViewPlayer1)
        self.graphicsViewPlayer2 = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsViewPlayer2.setEnabled(True)
        self.graphicsViewPlayer2.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.graphicsViewPlayer2.setObjectName("graphicsViewPlayer2")
        self.horizontalLayout.addWidget(self.graphicsViewPlayer2)
        TIPE.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(TIPE)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1083, 16))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        TIPE.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(TIPE)
        self.mainToolBar.setObjectName("mainToolBar")
        TIPE.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(TIPE)
        self.statusBar.setObjectName("statusBar")
        TIPE.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(TIPE)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(TIPE)
        QtCore.QMetaObject.connectSlotsByName(TIPE)

    def retranslateUi(self, TIPE):
        _translate = QtCore.QCoreApplication.translate
        TIPE.setWindowTitle(_translate("TIPE", "MainWindow"))
        self.labelView.setText(_translate("TIPE", "View"))
        self.pushButtonViewDefault.setText(_translate("TIPE", "Default"))
        self.pushButtonViewPlayer1.setText(_translate("TIPE", "Player 1"))
        self.pushButtonViewPlayer2.setText(_translate("TIPE", "Player 2"))
        self.labelPlayer1.setText(_translate("TIPE", "Player 1"))
        self.labelPlayer2.setText(_translate("TIPE", "Player 2"))
        self.pushButtonNewGame.setText(_translate("TIPE", "New Game"))
        self.labelMinimaxDepthPlayer1.setText(_translate("TIPE", "Depth"))
        self.labelMinimaxDepthPlayer2.setText(_translate("TIPE", "Depth"))
        self.pushButtonPlay.setText(_translate("TIPE", "Play"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("TIPE", "test"))
        item = self.listWidget.item(1)
        item.setText(_translate("TIPE", "azaz"))
        item = self.listWidget.item(2)
        item.setText(_translate("TIPE", "azaz"))
        item = self.listWidget.item(3)
        item.setText(_translate("TIPE", "dsfd"))
        item = self.listWidget.item(4)
        item.setText(_translate("TIPE", "dfdf"))
        item = self.listWidget.item(5)
        item.setText(_translate("TIPE", "qsd"))
        item = self.listWidget.item(6)
        item.setText(_translate("TIPE", "&"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.menuFile.setTitle(_translate("TIPE", "File"))
        self.actionOpen.setText(_translate("TIPE", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TIPE = QtWidgets.QMainWindow()
    ui = Ui_TIPE()
    ui.setupUi(TIPE)
    TIPE.show()
    sys.exit(app.exec_())

